Added new programs to exercises and learning packages
marekk1992/JavaMasterclass_Section5 pull request #3
Opened 2022-01-29 15:20 UTC by marekk1992

2022-01-29 15:44 UTC, RobertasVainickas requested changes

2022-01-29 15:44 UTC, RobertasVainickas commented on src/exercises/largestPrime/LargestPrime.java
> +                if (isPrime(i)) {
I would combine those two if statements into one

2022-01-29 21:40 UTC, marekk1992 commented on src/exercises/largestPrime/LargestPrime.java
> +                if (isPrime(i)) {
Fixed and removed method version2.

2022-01-30 15:24 UTC, RobertasVainickas approved these changes

2022-01-30 16:08 UTC, merged